name: FancyPerks
main: de.oliver.fancyperks.FancyPerks
author: OliverHD
version: 1.0.2
api-version: 1.19
folia-supported: true
loadbefore:
  - Vault
  - Essentials
  - LuckPerms
commands:
  FancyPerks:
    permission: FancyPerks.admin
  Perks:
    aliases:
      - perk